### ISSUE TITLE
CRITICAL! Example modules no longer work when using Flex 9.1.9

### ISSUE THREAD

**Issue by rmlockwood** [cdfarrow/flextools#14]
From some emails I've seen, icu.net got upgraded to version 2.8.0.158

Here's output from a colleague:
Traceback (most recent call last):
  File "C:\Users\Colleague\Documents\FLExTrans Work\FlexTools2.0 Exercise\FlexTools\FLExTools.py", line 584, in <module>
    main()
  File "C:\Users\Colleague\Documents\FLExTrans Work\FlexTools2.0 Exercise\FlexTools\FLExTools.py", line 574, in main
    FLExInit.Initialize()
  File "C:\Python37-32\lib\site-packages\flexlibs\FLExInit.py", line 47, in Initialize
    FwUtils.InitializeIcu()
System.IO.FileNotFoundException: Could not load file or assembly 'icu.net, Version=2.7.0.0, Culture=neutral, PublicKeyToken=416fdd914afa6b66' or one of its dependencies. The system cannot find the file specified.
   at SIL.LCModel.Core.Text.CustomIcu.InitIcuDataDir()
   at SIL.FieldWorks.Common.FwUtils.FwUtils.InitializeIcu() in c:\JenkinsSlaveHome\workspace\FieldWorks-Win-all-Release-Patch\Src\Common\FwUtils\FwUtils.cs:line 193

this actually came when she tried starting a FLExTrans collection.

**Comment by cdfarrow** [comment]
Fixed in flexlibs 1.1.1, which includes the old versions of the dlls that the Fieldworks libraries need.
