### ISSUE TITLE
FlexTools doesn't run with Python 3.11 (importlib error)

### ISSUE THREAD

**Issue by canilcomputer** [cdfarrow/flextools#42]
Running FlexTools gives the following error:

Traceback (most recent call last):
  File "F:\FlexTools\scripts\RunFlexTools.py", line 9, in <module>
    flextoolslib.main(Title)
  File "P:\Python311\Lib\site-packages\flextoolslib\code\FLExTools.py", line 135, in main
    mainForm = FTMainForm(appTitle, customMenu, statusbarCallback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\Python311\Lib\site-packages\flextoolslib\code\UIMain.py", line 612, in __init__
    self.__LoadModules()
  File "P:\Python311\Lib\site-packages\flextoolslib\code\UIMain.py", line 521, in __LoadModules
    errorList = self.moduleManager.LoadAll()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\Python311\Lib\site-packages\flextoolslib\code\FTModules.py", line 146, in LoadAll
    module = self.__importModule(moduleName, moduleFullPath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\Python311\Lib\site-packages\flextoolslib\code\FTModules.py", line 52, in __importModule
    spec = importlib.util.spec_from_file_location(moduleName, modulePath)
           ^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'util'

Adding
import importlib.util
to FTModules.py fixes the problem.

**Comment by cdfarrow** [comment]
Thanks for supplying the fix. I ran into this yesterday, but couldn't figure it out and the problem went away. It seems it was fragile (depended on other things importing importlib.util) (See https://discuss.python.org/t/python3-11-importlib-no-longer-exposes-util/25641)
